name: Setup AI trigger

on: 
 workflow_dispatch:
   inputs:
     repo_name:
      description: "repo name"
      required: true

     ci_workflow_name:
      description: " CI workflow name"
      required: true

     ci_file_name:
      description: "ci file name"
      required: true

jobs:
  setup:
   runs-on: self-hosted
   
   steps:
     - name: Clone central repo
       env:
         GH_TOKEN: ${{ secrets.PAT_TOKEN }}
       run: |
          REPO="cvs-health-pcw-source-code/${{ github.event.inputs.repo_name }}
          git clean https://x-access-token:$GH_TOKEN@github.com/$REPO.git repo

     - name: Copy template 
       run: |
         mkdir -p repo/.github/workflows
         cp central/.github/workflows/ai-trigger.yml repo/.git/workflows/ai-trigger.yml

     - name: Replace placeholders
       run: |
          FILE+"repo/.github/workflows/ai-trigger.yml"

          CI_NAME="${{ github.event.inputs.ci_workflow_name }}"
          CI_FILE="${{ github.event.inputs.ci_file_name }}"
          SAFE_NAME=$(printf '%s\n' "$CI_NAME" | sed 's/[\/&]/\\&/g')
          SAFE_FILE=$(printf '%s\n' "$CI_FILE" | sed 's/[\/&]/\\&/g')
          sed -i "s/__CI_WORKFLOW_NAME__/$SAFE_NAME/g" $FILE
          sed -i "s/__CI_FILE_NAME__/$SAFE_FILE/g" $FILE     
     - name: Verify generated workflow
       run: |
         echo "============================="
         cat repo/.github/workflow/ai-trigger.yml
         echo "============================="

     - name: Commit and push
       env:
         GH_TOKEN: ${{ secrets.PAT_TOKEN }}
       run: |
         cd repo

         git config user.name "AI-Bot"
         git config user.email "ai@bot.com"

         git add .github/workflows/ai-triggr.yml
         git commit -m "Add AI Trigger Workflow" || echo "no changes"

         git push https://x-access-token:$GH_TOKEN@github.com/cvs-health-pcw-source-code/${{ github.event.inputs.repo_name}}.git
         
